Fix and test for unmounted component warning
podefr/react-debounce-render pull request #6
Opened 2018-04-02 02:40 UTC by mjhm

fix for https://github.com/podefr/react-debounce-render/issues/5

2018-04-03 03:00 UTC, podefr requested changes
good catch on the warning! I've added a couple of comments to the PR, let me know if you can address them or would like me to. thanks!

2018-04-03 03:00 UTC, podefr commented on src/index.js
> +            this._isMounted = false;
Thanks again for spotting the warning and suggesting a fix!

It looks like the issue is that a previously scheduled call to setState() triggers after the component is unmounted, which then shows the warning. The warning indicates a bigger problem that can lead to another issue such as a memory leak. isMounted() was part of the react API but was deprecated because it shouldn't be used to avoid calls to setState: https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html, which implies that any similar pattern should be avoid.

The fix should actually be to cancel the debounce when the component unmounts, which also doesn't require us to track the mounted state of the component.

Given that the component is using lodash' debounce, it is in fact cancelable: `https://lodash.com/docs#debounce`
Would you mind trying `this.updateState.cancel()` in `componentWillUnmount` instead and let me know if it also fixes the issue in your application?

2018-04-03 03:00 UTC, podefr commented on e2e/src/unmount.test.js
> +    it('does not throw an unmounted component error', async () => {
thanks for adding a test! 

Would you mind moving it to App.test.js? given the limited amount of tests and the code duplication in the setup/teardown I'd rather have the 2 tests collocated.

Also, it seems that the test doesn't fail if the error is logged, meaning that even without the fix the test would still pass.
We should instead spy on console.error, schedule an unmount at 90ms and test after triggering the timers if an error was logged.
 
Something like this:

```
    describe('When unmounts before a scheduled call to setState', () => {
        beforeEach(() => {
            jest.spyOn(global.console, 'error');
            setTimeout(() => wrapper.unmount(), 90);
            jest.runAllTimers();
        });

        it(`Doesn't log an error`, () => {
            expect(global.console.error).not.toHaveBeenCalled();
        });
    });
```

could you update your PR with the change?

Thanks!

2018-04-03 03:35 UTC, mjhm commented
Thanks for the feedback.  This fix is definitely cleaner.  I also fixed the test.  The original code wasn't really failing.  It was just printing the warning while the test was passing.

2018-04-04 01:02 UTC, podefr commented
Thanks a lot @mjhm! I'll merge the PR and will push a new version (4.0.1) soon.

2018-04-04 01:05 UTC, podefr approved these changes

2018-04-04 01:05 UTC, merged